version: '3.8'

services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    image: survey-backend
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
