version: '3.8'

services:
  backend:
    build: ./backend
    image: survey-backend
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootUser
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: surveyDB
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.runCommand({ ping: 1 }).ok']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge
