openapi: 3.1.0
info:
  title: API de Pesquisas
  version: 1.0.0
  description: API para gestão de pesquisas

servers:
  - url: http://localhost:5000
    description: Servidor local de desenvolvimento

paths:
  /survey:
    post:
      summary: Cria uma nova pesquisa
      tags:
        - Pesquisas
      requestBody:
        description: Dados da nova pesquisa
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSurvey'
            examples:
              Success:
                value:
                  target: "Clientes"
                  questions:
                    - "Qual é o seu nível de satisfação?"
                    - "Recomendaria nossos serviços?"
      responses:
        '201':
          description: Pesquisa criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
              examples:
                Success:
                  value:
                    id: "e6690315-f4a0-41ce-bdd6-fd90d6596bf4"
                    target: "Clientes"
                    questions:
                      - "Qual é o seu nível de satisfação?"
                      - "Recomendaria nossos serviços?"
        '400':
          description: Erro de solicitação inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                erroExemplo:
                  value:
                    httpCode: "400"
                    msg: [ "body.target is a required field" ]

  /survey/{survey_id}/answer:
    get:
      summary: Lista todas as respostas da pesquisa
      tags:
        - Pesquisas
      parameters:
        - in: query
          name: sortStars
          required: false
          schema:
            type: string
            enum: [asc, desc]
          description: Ordenação dos resultados, 'asc' para ascendente e 'desc' para descendente
        - in: path
          name: survey_id
          required: true
          schema:
            type: string
          description: ID da Pesquisa
      responses:
        '200':
          description: Lista de respostas da pesquisa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SurveyAnswer'
              examples:
                Success:
                  value:
                    - id: "e6690315-f4a0-41ce-bdd6-fd90d6596bf4"
                      email: "exemplo1@dominio.com"
                      rate: 4.5
                      answers:
                        - question: "Qual é o seu nível de satisfação?"
                          answer: "Muito satisfeito"
                    - id: "4bfceef9-9e43-4d67-9b7b-6f53e7f18508"
                      email: "exemplo2@dominio.com"
                      rate: 4.0
                      answers:
                        - question: "Qual é o seu nível de satisfação?"
                          answer: "Satisfeito"
        '404':
          description: Pesquisa não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                erroExemplo:
                  value:
                    httpCode: "404"
                    msg: "A Pesquisa não existe"

    post:
      summary: Responde a pesquisa
      tags:
        - Pesquisas
      parameters:
        - in: path
          name: survey_id
          required: true
          schema:
            type: string
          description: ID da Pesquisa
      requestBody:
        description: Resposta da pesquisa
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SurveyAnswer'
            examples:
              Success:
                value:
                  email: "respondente@dominio.com"
                  rate: 5
                  answers:
                    - question: "Qual é o seu nível de satisfação?"
                      answer: "Muito satisfeito"
      responses:
        '200':
          description: Pesquisa respondida com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SurveyAnswer'
              examples:
                Success:
                  value:
                    id: "e6690315-f4a0-41ce-bdd6-fd90d6596bf4"
                    email: "respondente@dominio.com"
                    rate: 5
                    answers:
                      - question: "Qual é o seu nível de satisfação?"
                        answer: "Muito satisfeito"
        '404':
          description: Pesquisa não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                erroExemplo:
                  value:
                    httpCode: "404"
                    msg: "Pesquisa não encontrada."

  /survey/{survey_id}:
    patch:
      summary: Atualiza a pesquisa de um curso
      tags:
        - Pesquisas
      parameters:
        - in: path
          name: survey_id
          required: true
          schema:
            type: string
          description: ID da Pesquisa
      requestBody:
        description: Dados atualizados da pesquisa
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSurvey'
            examples:
              Success:
                value:
                  target: "Funcionários"
                  questions:
                    - "Como você avalia o ambiente de trabalho?"
      responses:
        '200':
          description: Pesquisa atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
              examples:
                Success:
                  value:
                    id: "e6690315-f4a0-41ce-bdd6-fd90d6596bf4"
                    target: "Funcionários"
                    questions:
                      - "Como você avalia o ambiente de trabalho?"
        '404':
          description: Pesquisa não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                erroExemplo:
                  value:
                    httpCode: "404"
                    msg: "Pesquisa não encontrada."

components:
  schemas:
    Survey:
      type: object
      properties:
        id:
          type: string
        target:
          type: string
        questions:
          type: array
          items:
            type: string

    NewSurvey:
      type: object
      properties:
        target:
          type: string
        questions:
          type: array
          items:
            type: string

    SurveyAnswer:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        rate:
          type: number
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'

    Answer:
      type: object
      properties:
        question:
          type: string
        answer:
          type: string

    Error:
      type: object
      properties:
        httpCode:
          type: string
        msg:
          oneOf:
            - type: string
            - type: array
              items:
                type: string
